openapi: 3.1.0
info:
  title: 'lemon.markets Brokerage API 🍋 Accounts: General Workflows API'
  version: 0.1.0
  description: Use workflows to perform repetitive tasks automatically.
servers:
- url: https://sandbox.api.lemon.markets/v1
  description: Sandbox
tags:
- name: Workflows
  description: Use workflows to perform repetitive tasks automatically.
paths:
  /accounts/{account_id}/workflows/{workflow_id}/cancel:
    post:
      tags:
      - Workflows
      summary: Cancel Workflow
      operationId: cancel_workflow
      parameters:
      - name: account_id
        required: true
        schema:
          title: Account Identifier
          type: string
        in: path
        example: cusa_20323d55bb264d42b0b225d293591049
        description: 'An account identifier.

          '
      - name: unified_orders
        in: query
        required: false
        schema:
          type: boolean
          default: false
          title: Unified Orders
        description: 'Use new unified `order` API instead of the `batch_order` API.

          '
      - name: workflow_id
        in: path
        required: true
        schema:
          type: string
          title: Workflow Identifier
        description: 'A workflow identifier.

          '
      - name: LMG-Data-Privacy-Access-Principal
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Principal
      - name: LMG-Data-Privacy-Access-Justification
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Justification
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerWorkflowResponse'
              example:
                action:
                  amount: '1.25'
                  currency: EUR
                  fee: '0.00'
                  instrument: LU0290358497
                  side: buy
                  type: batch_order.create_and_confirm
                history:
                - status: canceled
                  timestamp: '2024-04-23T11:30:20.434025+00:00'
                - status: created
                  timestamp: '2024-04-23T11:00:12.152244+00:00'
                id: wf_f2aa90bcc16a43ddb2098c8a5da9f55b
                trigger:
                  cadence: monthly
                  type: schedule
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unprocessable Entity
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Server Error
  /accounts/{account_id}/workflows/{workflow_id}/confirm:
    post:
      tags:
      - Workflows
      summary: Confirm Workflow
      operationId: confirm_workflow
      parameters:
      - name: account_id
        required: true
        schema:
          title: Account Identifier
          type: string
        in: path
        example: cusa_20323d55bb264d42b0b225d293591049
        description: 'An account identifier.

          '
      - name: unified_orders
        in: query
        required: false
        schema:
          type: boolean
          default: false
          title: Unified Orders
        description: 'Use new unified `order` API instead of the `batch_order` API.

          '
      - name: workflow_id
        in: path
        required: true
        schema:
          type: string
          title: Workflow Identifier
        description: 'A workflow identifier.

          '
      - name: LMG-Data-Privacy-Access-Principal
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Principal
      - name: LMG-Data-Privacy-Access-Justification
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Justification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmCustomerWorkflowRequest'
            example:
              appropriateness_consent: true
              sca:
                client_credential_id: local_authenticator_id
                signature: <base64>
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerWorkflowResponse'
              example:
                action:
                  amount: '5.00'
                  currency: EUR
                  fee: '0.10'
                  instrument: IE00BYXYX521
                  side: buy
                  type: batch_order.create_and_confirm
                history:
                - status: confirmed
                  timestamp: '2024-04-19T07:49:22.783350+00:00'
                - status: created
                  timestamp: '2024-04-19T07:34:37.359894+00:00'
                id: wf_acb4235bf09342b6a3b3d1401ae7576f
                trigger:
                  cadence: monthly
                  type: schedule
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unprocessable Entity
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Server Error
  /accounts/{account_id}/workflows:
    post:
      tags:
      - Workflows
      summary: Create Workflow
      operationId: create_workflow
      parameters:
      - name: account_id
        required: true
        schema:
          title: Account Identifier
          type: string
        in: path
        example: cusa_20323d55bb264d42b0b225d293591049
        description: 'An account identifier.

          '
      - name: unified_orders
        in: query
        required: false
        schema:
          type: boolean
          default: false
          title: Unified Orders
        description: 'Use new unified `order` API instead of the `batch_order` API.

          '
      - name: LMG-Data-Privacy-Access-Principal
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Principal
      - name: LMG-Data-Privacy-Access-Justification
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Justification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerWorkflowRequest'
            example:
              action:
                type: order.create_and_confirm
                order:
                  amount: '1.25'
                  currency: EUR
                  fee: '0.00'
                  instrument: LU0290358497
                  side: buy
                  type: batch
              trigger:
                cadence: monthly
                type: schedule
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerWorkflowResponse'
              example:
                action:
                  amount: '1.25'
                  currency: EUR
                  fee: '0.00'
                  instrument: LU0290358497
                  side: buy
                  type: batch_order.create_and_confirm
                appropriateness_consent:
                  required: false
                history:
                - status: created
                  timestamp: '2024-04-23T11:00:12.152244+00:00'
                id: wf_f2aa90bcc16a43ddb2098c8a5da9f55b
                regulatory_disclosures:
                  acquisition_costs: '0.00'
                  acquisition_costs_pct: '0.00'
                  custody_costs: '0.00'
                  custody_costs_pct: '0.00'
                  entry_costs: '0.00'
                  entry_costs_pct: '0.00'
                  estimated_amount: '1.25'
                  estimated_price: '141.3099'
                  estimated_quantity: '0.00885'
                  exit_costs: '0.00'
                  exit_costs_pct: '0.00'
                  impact_final_year: '0.00'
                  impact_final_year_pct: '0.00'
                  impact_first_year: '0.00'
                  impact_first_year_pct: '0.00'
                  impact_subsequent_year: '0.00'
                  impact_subsequent_year_pct: '0.10'
                  kid: https://kid.sandbox.lemon.markets/2023-11-17/LU0290358497-ac81558ef3e50c8eb4a01f7a68800963.pdf
                  product_costs: '0.00'
                  product_costs_pct: '0.10'
                  recurring_impact_total: '19.05'
                  recurring_impact_total_pct: '25.40'
                  recurring_impact_year_1: '0.81'
                  recurring_impact_year_1_pct: '5.40'
                  recurring_impact_year_2: '2.31'
                  recurring_impact_year_2_pct: '7.70'
                  recurring_impact_year_3: '3.81'
                  recurring_impact_year_3_pct: '8.47'
                  recurring_impact_year_4: '5.31'
                  recurring_impact_year_4_pct: '8.85'
                  recurring_impact_year_5: '6.81'
                  recurring_impact_year_5_pct: '9.08'
                  running_costs: '0.00'
                  running_costs_pct: '0.10'
                  service_costs_total: '0.00'
                  service_costs_total_pct: '0.03'
                  third_party_grants: '0.00'
                  third_party_grants_pct: '0.03'
                sca:
                  challenge: pVz8_N6cNdepukvaApmdww==
                  required: false
                trigger:
                  cadence: monthly
                  type: schedule
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unprocessable Entity
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Server Error
    get:
      tags:
      - Workflows
      summary: List Workflows
      operationId: list_workflows
      parameters:
      - name: account_id
        required: true
        schema:
          title: Account Identifier
          type: string
        in: path
        example: cusa_20323d55bb264d42b0b225d293591049
        description: 'An account identifier.

          '
      - name: cursor
        in: query
        required: false
        schema:
          type: string
          title: Cursor
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 1
          default: 100
          title: Limit
      - name: status
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/CustomerWorkflowStatus'
      - name: unified_orders
        in: query
        required: false
        schema:
          type: boolean
          default: false
          title: Unified Orders
        description: 'Use new unified `order` API instead of the `batch_order` API.

          '
      - name: LMG-Data-Privacy-Access-Principal
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Principal
      - name: LMG-Data-Privacy-Access-Justification
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Justification
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_CustomerWorkflowResponse_'
              example:
                data:
                - action:
                    amount: '5.00'
                    currency: EUR
                    fee: '0.10'
                    instrument: IE00BYXYX521
                    side: buy
                    type: batch_order.create_and_confirm
                  history:
                  - status: confirmed
                    timestamp: '2024-04-19T07:49:22.783350+00:00'
                  - status: created
                    timestamp: '2024-04-19T07:34:37.359894+00:00'
                  id: wf_acb4235bf09342b6a3b3d1401ae7576f
                  trigger:
                    cadence: monthly
                    type: schedule
                - action:
                    amount: '5.00'
                    currency: EUR
                    fee: '0.00'
                    instrument: IE00BYXYX521
                    side: buy
                    type: batch_order.create_and_confirm
                  appropriateness_consent:
                    required: false
                  history:
                  - status: created
                    timestamp: '2024-04-19T07:33:57.802570+00:00'
                  id: wf_41bfe60078764fca9bef7c3ed7d04c0d
                  regulatory_disclosures:
                    acquisition_costs: '0.00'
                    acquisition_costs_pct: '0.00'
                    custody_costs: '0.00'
                    custody_costs_pct: '0.00'
                    entry_costs: '0.00'
                    entry_costs_pct: '0.00'
                    estimated_amount: '5.00'
                    estimated_price: '28.3988'
                    estimated_quantity: '0.17606'
                    exit_costs: '0.00'
                    exit_costs_pct: '0.00'
                    impact_final_year: '0.00'
                    impact_final_year_pct: '0.00'
                    impact_first_year: '0.00'
                    impact_first_year_pct: '0.00'
                    impact_subsequent_year: '0.01'
                    impact_subsequent_year_pct: '0.19'
                    kid: https://kid.sandbox.lemon.markets/2023-11-17/IE00BYXYX521-5f534eec417153a5f638ad091f0a2962.pdf
                    product_costs: '0.01'
                    product_costs_pct: '0.19'
                    recurring_impact_total: '144.90'
                    recurring_impact_total_pct: '48.30'
                    recurring_impact_year_1: '6.18'
                    recurring_impact_year_1_pct: '10.30'
                    recurring_impact_year_2: '17.58'
                    recurring_impact_year_2_pct: '14.65'
                    recurring_impact_year_3: '28.98'
                    recurring_impact_year_3_pct: '16.10'
                    recurring_impact_year_4: '40.38'
                    recurring_impact_year_4_pct: '16.83'
                    recurring_impact_year_5: '51.78'
                    recurring_impact_year_5_pct: '17.26'
                    running_costs: '0.01'
                    running_costs_pct: '0.19'
                    service_costs_total: '0.00'
                    service_costs_total_pct: '0.03'
                    third_party_grants: '0.00'
                    third_party_grants_pct: '0.03'
                  sca:
                    challenge: FxvVWk3iLDqiz3QJaxPLQg==
                    required: false
                  trigger:
                    cadence: monthly
                    type: schedule
                pagination: {}
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unprocessable Entity
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Server Error
  /accounts/{account_id}/workflows/{workflow_id}:
    get:
      tags:
      - Workflows
      summary: Get Workflow
      operationId: get_workflow
      parameters:
      - name: account_id
        required: true
        schema:
          title: Account Identifier
          type: string
        in: path
        example: cusa_20323d55bb264d42b0b225d293591049
        description: 'An account identifier.

          '
      - name: unified_orders
        in: query
        required: false
        schema:
          type: boolean
          default: false
          title: Unified Orders
        description: 'Use new unified `order` API instead of the `batch_order` API.

          '
      - name: workflow_id
        in: path
        required: true
        schema:
          type: string
          title: Workflow Identifier
        description: 'A workflow identifier.

          '
      - name: LMG-Data-Privacy-Access-Principal
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Principal
      - name: LMG-Data-Privacy-Access-Justification
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Justification
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerWorkflowResponse'
              example:
                action:
                  amount: '5.00'
                  currency: EUR
                  fee: '0.00'
                  instrument: IE00BYXYX521
                  side: buy
                  type: batch_order.create_and_confirm
                appropriateness_consent:
                  required: false
                history:
                - status: created
                  timestamp: '2024-04-19T07:33:57.802570+00:00'
                id: wf_41bfe60078764fca9bef7c3ed7d04c0d
                regulatory_disclosures:
                  acquisition_costs: '0.00'
                  acquisition_costs_pct: '0.00'
                  custody_costs: '0.00'
                  custody_costs_pct: '0.00'
                  entry_costs: '0.00'
                  entry_costs_pct: '0.00'
                  estimated_amount: '5.00'
                  estimated_price: '28.3988'
                  estimated_quantity: '0.17606'
                  exit_costs: '0.00'
                  exit_costs_pct: '0.00'
                  impact_final_year: '0.00'
                  impact_final_year_pct: '0.00'
                  impact_first_year: '0.00'
                  impact_first_year_pct: '0.00'
                  impact_subsequent_year: '0.01'
                  impact_subsequent_year_pct: '0.19'
                  kid: https://kid.sandbox.lemon.markets/2023-11-17/IE00BYXYX521-5f534eec417153a5f638ad091f0a2962.pdf
                  product_costs: '0.01'
                  product_costs_pct: '0.19'
                  recurring_impact_total: '144.90'
                  recurring_impact_total_pct: '48.30'
                  recurring_impact_year_1: '6.18'
                  recurring_impact_year_1_pct: '10.30'
                  recurring_impact_year_2: '17.58'
                  recurring_impact_year_2_pct: '14.65'
                  recurring_impact_year_3: '28.98'
                  recurring_impact_year_3_pct: '16.10'
                  recurring_impact_year_4: '40.38'
                  recurring_impact_year_4_pct: '16.83'
                  recurring_impact_year_5: '51.78'
                  recurring_impact_year_5_pct: '17.26'
                  running_costs: '0.01'
                  running_costs_pct: '0.19'
                  service_costs_total: '0.00'
                  service_costs_total_pct: '0.03'
                  third_party_grants: '0.00'
                  third_party_grants_pct: '0.03'
                sca:
                  challenge: FxvVWk3iLDqiz3QJaxPLQg==
                  required: false
                trigger:
                  cadence: monthly
                  type: schedule
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unprocessable Entity
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Server Error
components:
  schemas:
    AppropriatenessConsentResponse:
      title: AppropriatenessConsentResponse
      description: 'An object representing the requirements for explicit confirmation of an appropriateness warning.

        '
      type: object
      properties:
        required:
          type: boolean
          title: Consent Required
          description: 'Requirement indicator for the appropriateness warning.

            **NOTE:** If this value is `true`, the frontend must present a warning to the user as outlined in your onboarding documentation.

            '
      required:
      - required
    ActionDataResponse:
      properties:
        type:
          $ref: '#/components/schemas/ActionType'
        order:
          $ref: '#/components/schemas/OrderDataResponse'
      type: object
      required:
      - type
      - order
      description: 'An object representing a workflow action.

        '
      title: ActionDataResponse
    Page_CustomerWorkflowResponse_:
      title: Page of CustomerWorkflowResponse
      required:
      - data
      - pagination
      type: object
      properties:
        data:
          title: Data
          description: 'The elements of the response.

            '
          type: array
          items:
            $ref: '#/components/schemas/CustomerWorkflowResponse'
        pagination:
          $ref: '#/components/schemas/Pagination'
    CustomerWorkflowStatus:
      type: string
      enum:
      - canceled
      - confirmed
      - created
      title: CustomerWorkflowStatus
      description: 'A category representing a workflow status:

        <ul> <li><code>canceled</code> <li><code>confirmed</code> <li><code>created</code> </ul>

        '
    broker__apps__api__endpoints__customer_workflows__RegulatoryDisclosureResponse:
      properties:
        kid:
          type: string
          title: Kid
        estimated_price:
          type: string
          title: Estimated Price
        estimated_quantity:
          type: string
          title: Estimated Quantity
        estimated_amount:
          type: string
          title: Estimated Amount
        service_costs_total:
          type: string
          title: Service Costs Total
        service_costs_total_pct:
          type: string
          title: Service Costs Total Pct
        entry_costs:
          type: string
          title: Entry Costs
        entry_costs_pct:
          type: string
          title: Entry Costs Pct
        third_party_grants:
          type: string
          title: Third Party Grants
        third_party_grants_pct:
          type: string
          title: Third Party Grants Pct
        acquisition_costs:
          type: string
          title: Acquisition Costs
        acquisition_costs_pct:
          type: string
          title: Acquisition Costs Pct
        custody_costs:
          type: string
          title: Custody Costs
        custody_costs_pct:
          type: string
          title: Custody Costs Pct
        product_costs:
          type: string
          title: Product Costs
        product_costs_pct:
          type: string
          title: Product Costs Pct
        running_costs:
          type: string
          title: Running Costs
        running_costs_pct:
          type: string
          title: Running Costs Pct
        exit_costs:
          type: string
          title: Exit Costs
        exit_costs_pct:
          type: string
          title: Exit Costs Pct
        impact_first_year:
          type: string
          title: Impact First Year
        impact_first_year_pct:
          type: string
          title: Impact First Year Pct
        impact_subsequent_year:
          type: string
          title: Impact Subsequent Year
        impact_subsequent_year_pct:
          type: string
          title: Impact Subsequent Year Pct
        impact_final_year:
          type: string
          title: Impact Final Year
        impact_final_year_pct:
          type: string
          title: Impact Final Year Pct
        recurring_impact_year_1:
          type: string
          title: Recurring Impact First Year
        recurring_impact_year_1_pct:
          type: string
          title: Recurring Impact First Year Pct
        recurring_impact_year_2:
          type: string
          title: Recurring Impact Second Year
        recurring_impact_year_2_pct:
          type: string
          title: Recurring Impact Second Year Pct
        recurring_impact_year_3:
          type: string
          title: Recurring Impact Third Year
        recurring_impact_year_3_pct:
          type: string
          title: Recurring Impact Third Year Pct
        recurring_impact_year_4:
          type: string
          title: Recurring Impact Fourth Year
        recurring_impact_year_4_pct:
          type: string
          title: Recurring Impact Fourth Year Pct
        recurring_impact_year_5:
          type: string
          title: Recurring Impact Fifth Year
        recurring_impact_year_5_pct:
          type: string
          title: Recurring Impact Fifth Year Pct
        recurring_impact_total:
          type: string
          title: Recurring Impact Total
        recurring_impact_total_pct:
          type: string
          title: Recurring Impact Total Pct
      type: object
      required:
      - acquisition_costs
      - acquisition_costs_pct
      - custody_costs
      - custody_costs_pct
      - entry_costs
      - entry_costs_pct
      - estimated_price
      - estimated_quantity
      - estimated_amount
      - exit_costs
      - exit_costs_pct
      - impact_first_year
      - impact_first_year_pct
      - impact_subsequent_year
      - impact_subsequent_year_pct
      - impact_final_year
      - impact_final_year_pct
      - product_costs
      - product_costs_pct
      - recurring_impact_year_1
      - recurring_impact_year_1_pct
      - recurring_impact_year_2
      - recurring_impact_year_2_pct
      - recurring_impact_year_3
      - recurring_impact_year_3_pct
      - recurring_impact_year_4
      - recurring_impact_year_4_pct
      - recurring_impact_year_5
      - recurring_impact_year_5_pct
      - recurring_impact_total
      - recurring_impact_total_pct
      - running_costs
      - running_costs_pct
      - service_costs_total
      - service_costs_total_pct
      - third_party_grants
      - third_party_grants_pct
      title: RegulatoryDisclosureResponse
    Side:
      type: string
      enum:
      - buy
      - sell
      title: Side
      description: 'A category to represent the side of a customer''s order:

        <ul> <li><code>buy</code>: Buy shares of an instrument and pay with cash. <li><code>sell</code>: Sell shares of an instrument and receive cash. </ul>

        '
    TriggerType:
      type: string
      const: schedule
      title: TriggerType
      description: 'A category representing the type of the trigger:

        <ul> <li><code>schedule</code> </ul>

        '
    ScheduledCadenceType:
      type: string
      enum:
      - monthly
      - daily
      title: ScheduledCadenceType
      description: 'A category describing the cadence for scheduled workflows:

        <ul> <li><code>daily</code>: Execute every Trading Day (Sandbox-only) <li><code>monthly</code>: Execute once every Month, on the first trading day </ul>

        '
    TriggerRequest:
      properties:
        type:
          $ref: '#/components/schemas/TriggerType'
        cadence:
          $ref: '#/components/schemas/ScheduledCadenceType'
        start_after:
          type: string
          format: date
          title: Start After
          description: 'Block workflow execution until the date specified here.  This date specifies the last day that the trigger should not be activated.  If you want to block a workflow for July 2025, you can pass 2025-07-31 and the trigger will not be activated before 2025-08-01.

            '
      type: object
      required:
      - type
      - cadence
      title: TriggerRequest
      description: 'A workflow trigger.  This structure represents the way that the workflow is started.

        '
    OrderDataResponse:
      properties:
        type:
          $ref: '#/components/schemas/WorkflowOrderType'
        side:
          $ref: '#/components/schemas/Side'
        instrument:
          type: string
          pattern: ^[A-Z]{2}[0-9A-Z]{9}[0-9]$
          title: Instrument
          description: 'An ISIN (International Securities Identification Number) according to ISO 6166.  The ISIN specifies the instrument for the order.

            '
        securities_account:
          type: string
          title: Securities Account Identifier
          description: 'A securities account identifier.  Use this property to specify the securities account for order execution and settlement.  If the customer has only one securities account, this property is optional.  If the customer has more than one securities account, this property is required.

            '
        amount:
          type: string
          format: number
          title: Amount
          description: 'The amount of money to invest with each order.

            '
        fee:
          type: string
          format: number
          title: Fee
          description: 'The fee that will be charged by lemon.markets on your behalf.

            '
        currency:
          type: string
          maxLength: 3
          minLength: 3
          title: Currency
          description: 'An ISO 4217 three-letter currency code. Its value represents the currency for the `fee`, `fees.base_amount` and `amount` listed here. The only currently available currency is `"EUR"`.

            '
      type: object
      required:
      - type
      - side
      - instrument
      - amount
      - fee
      - currency
      title: OrderDataResponse
      description: 'An object describing an order to be created as the result of a workflow action.

        '
    StatusChange_CustomerWorkflowStatus_:
      properties:
        status:
          $ref: '#/components/schemas/CustomerWorkflowStatus'
        timestamp:
          type: string
          format: date-time
          title: Timestamp
          description: 'The timestamp of the event.  It represents the point in time at which the workflow was updated.

            '
          example: '2023-06-23T07:29:55.465000+00:00'
      type: object
      required:
      - status
      - timestamp
      title: StatusChange[CustomerWorkflowStatus]
    SCAConfirmation:
      title: Strong Customer Authentication
      description: 'An object representing the confirmation for strong customer authentication.

        '
      properties:
        client_credential_id:
          type: string
          title: Client Credential Identifier
          description: 'The client-side identifier of the authenticator used to generate the signature.

            '
        signature:
          type: string
          title: Signature
          description: 'The base64-url encoded DER form of the signature for `challenge` using the private key for the public key that was registered as an authenticator.

            '
      type: object
      required:
      - client_credential_id
      - signature
    ErrorResponse:
      title: ErrorResponse
      required:
      - message
      type: object
      properties:
        message:
          title: Message
          type: string
    ConfirmCustomerWorkflowRequest:
      properties:
        appropriateness_consent:
          type: boolean
          title: Appropriateness Consent
        sca:
          $ref: '#/components/schemas/SCAConfirmation'
      type: object
      title: ConfirmCustomerWorkflowRequest
    WorkflowOrderType:
      type: string
      enum:
      - batch
      title: WorkflowOrderType
      description: 'The order type for a scheduled workflow.  Only <code>batch</code> is supported: orders created by workflows are collected across customers and executed as one composite order.  (Market orders are not available for scheduled workflows.)

        '
    OrderDataRequest:
      properties:
        type:
          $ref: '#/components/schemas/WorkflowOrderType'
        side:
          $ref: '#/components/schemas/Side'
        instrument:
          type: string
          pattern: ^[A-Z]{2}[0-9A-Z]{9}[0-9]$
          title: Instrument
          description: 'An ISIN (International Securities Identification Number) according to ISO 6166.  The ISIN specifies the instrument for the order.

            '
        securities_account:
          type: string
          title: Securities Account Identifier
          description: 'A securities account identifier.  Use this property to specify the securities account for order execution and settlement.  If the customer has only one securities account, this property is optional.  If the customer has more than one securities account, this property is required.

            '
        amount:
          type: string
          format: number
          exclusiveMinimum: 0
          title: Amount
          description: 'The amount of money to invest with each order.

            '
        fee:
          type: string
          format: number
          minimum: 0
          title: Fee
          description: 'The fee that will be charged by lemon.markets on your behalf.

            '
        currency:
          type: string
          maxLength: 3
          minLength: 3
          title: Currency
          description: 'An ISO 4217 three-letter currency code. Its value represents the currency for the `fee`, `fees.base_amount` and `amount` listed here. The only currently available currency is `"EUR"`.

            '
      type: object
      required:
      - type
      - side
      - instrument
      - amount
      - fee
      - currency
      description: 'An object describing an order to be created as the result of a workflow action.

        '
      title: OrderDataRequest
    TriggerResponse:
      properties:
        type:
          $ref: '#/components/schemas/TriggerType'
        cadence:
          $ref: '#/components/schemas/ScheduledCadenceType'
        start_after:
          type: string
          format: date
          title: Start After
          description: 'Block workflow execution until the date specified here.  This date specifies the last day that the trigger should not be activated.  If you want to block a workflow for July 2025, you can pass 2025-07-31 and the trigger will not be activated before 2025-08-01.

            '
      type: object
      required:
      - type
      - cadence
      title: TriggerResponse
    CustomerWorkflowResponse:
      properties:
        id:
          type: string
          title: Identifier
          description: 'A value identifiying the workflow.

            '
        trigger:
          $ref: '#/components/schemas/TriggerResponse'
        action:
          $ref: '#/components/schemas/ActionDataResponse'
        regulatory_disclosures:
          $ref: '#/components/schemas/broker__apps__api__endpoints__customer_workflows__RegulatoryDisclosureResponse'
        sca:
          $ref: '#/components/schemas/SCAResponse'
        appropriateness_consent:
          $ref: '#/components/schemas/AppropriatenessConsentResponse'
        history:
          items:
            $ref: '#/components/schemas/StatusChange_CustomerWorkflowStatus_'
          type: array
          title: History
      type: object
      required:
      - id
      - trigger
      - action
      - history
      title: CustomerWorkflowResponse
    ActionType:
      type: string
      enum:
      - order.create_and_confirm
      - batch_order.create_and_confirm
      title: ActionType
      description: 'A category representing a workflow action type:

        <ul> <li><code>batch_order.create_and_confirm</code>: Legacy identifier to create batch-order based workflows (deprecated since 2024-06; use `order.create_and_confirm` instead). <li><code>order.create_and_confirm</code> </ul>

        '
    ActionDataRequest:
      properties:
        type:
          $ref: '#/components/schemas/ActionType'
        order:
          $ref: '#/components/schemas/OrderDataRequest'
      type: object
      required:
      - type
      - order
      description: 'An object representing a workflow action.

        '
      title: ActionDataRequest
    CreateCustomerWorkflowRequest:
      properties:
        trigger:
          $ref: '#/components/schemas/TriggerRequest'
        action:
          $ref: '#/components/schemas/ActionDataRequest'
      type: object
      required:
      - trigger
      - action
      title: CreateCustomerWorkflowRequest
    Pagination:
      title: Pagination
      type: object
      properties:
        next_cursor:
          title: Cursor for Next Page
          type: string
          description: 'When fetching long lists of elements, you can use our pagination feature to fetch batches of data.  If a response contains the property `pagination.next_cursor`, you can pass its value via the query item `cursor` to generate the request for the next batch of data.

            '
      description: 'Information about accessing elements beyond the ones that were returned.

        '
      example:
        next_cursor: <opaque-data>
    SCAResponse:
      properties:
        required:
          type: boolean
          title: Required
        challenge:
          type: string
          title: Challenge
      type: object
      required:
      - required
      - challenge
      title: SCAResponse
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
