openapi: 3.1.0
info:
  title: 'lemon.markets Brokerage API 🍋 Accounts: General Batch Orders API'
  version: 0.1.0
servers:
- url: https://sandbox.api.lemon.markets/v1
  description: Sandbox
tags:
- name: Batch Orders
paths:
  /accounts/{account_id}/batch_orders/{order_id}/cancel:
    post:
      summary: Cancel Batch Order
      tags:
      - Batch Orders
      operationId: cancel_batch_order
      parameters:
      - name: account_id
        required: true
        schema:
          title: Account Identifier
          type: string
        in: path
        example: cusa_c2c3f89ec0524b6e818ce00c16e4897f
        description: 'An account identifier.

          '
      - name: order_id
        required: true
        schema:
          type: string
          title: Order Identifier
        in: path
        example: bord_0fef2e8b7962404d94454d8c47caa364
        description: 'A batch order identifier.

          '
      - name: LMG-Data-Privacy-Access-Principal
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Principal
      - name: LMG-Data-Privacy-Access-Justification
        in: header
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Justification
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchOrderResponse'
              example:
                amount: '500.00'
                appropriateness_check:
                  consent_confirmed_at: null
                  consent_required: false
                created_at: '2024-04-12T13:44:37.315658+00:00'
                currency: EUR
                fee: '1.00'
                history:
                - status: canceling
                  timestamp: '2024-04-12T13:50:41.639338+00:00'
                - status: accepted
                  timestamp: '2024-04-12T13:49:34.496380+00:00'
                - status: confirmed
                  timestamp: '2024-04-12T13:49:33.266583+00:00'
                - status: created
                  timestamp: '2024-04-12T13:44:37.315658+00:00'
                id: bord_61931714f0a44809bc423fccc82ccbbd
                instrument: IE00BYXYX521
                quantity: null
                regulatory_disclosures:
                  entry_costs: '1.00'
                  entry_costs_pct: '0.20'
                  estimated_amount: '500.00'
                  estimated_price: '28.6399'
                  estimated_quantity: '17.45816'
                  exit_costs: '1.00'
                  exit_costs_pct: '0.20'
                  impact_final_year: '1.00'
                  impact_final_year_pct: '0.20'
                  impact_first_year: '1.00'
                  impact_first_year_pct: '0.20'
                  impact_subsequent_year: '0.95'
                  impact_subsequent_year_pct: '0.19'
                  kid: https://kid.sandbox.lemon.markets/2023-11-17/IE00BYXYX521-5f534eec417153a5f638ad091f0a2962.pdf
                  product_costs: '0.95'
                  product_costs_pct: '0.19'
                  running_costs: '0.95'
                  running_costs_pct: '0.19'
                  service_costs_total: '1.15'
                  service_costs_total_pct: '0.23'
                  third_party_grants: '0.15'
                  third_party_grants_pct: '0.03'
                sca:
                  challenge: b42BB63kg24UPKLFX5CiMA==
                  required: false
                side: buy
                status: canceling
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unprocessable Entity
        5XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Server Error
  /accounts/{account_id}/batch_orders/{order_id}/confirm:
    post:
      summary: Confirm Batch Order
      tags:
      - Batch Orders
      operationId: confirm_batch_order
      parameters:
      - name: account_id
        required: true
        schema:
          title: Account Identifier
          type: string
        in: path
        example: cusa_c2c3f89ec0524b6e818ce00c16e4897f
        description: 'An account identifier.

          '
      - name: order_id
        required: true
        schema:
          type: string
          title: Order Identifier
        in: path
        example: bord_0fef2e8b7962404d94454d8c47caa364
        description: 'A batch order identifier.

          '
      - required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Principal
        name: LMG-Data-Privacy-Access-Principal
        in: header
      - required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Justification
        name: LMG-Data-Privacy-Access-Justification
        in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmBatchOrderRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchOrderResponse'
              example:
                amount: '50.00'
                appropriateness_check:
                  consent_confirmed_at: '2023-07-14T17:31:00.495533+00:00'
                  consent_required: true
                created_at: '2023-07-14T16:35:19.203369+00:00'
                currency: EUR
                fee: '0.50'
                history:
                - status: confirmed
                  timestamp: '2023-07-14T17:31:00.467252+00:00'
                - status: created
                  timestamp: '2023-07-14T16:35:19.203369+00:00'
                id: bord_0fef2e8b7962404d94454d8c47caa364
                instrument: IE00B441G979
                quantity: null
                regulatory_disclosures:
                  entry_costs: '0.50'
                  entry_costs_pct: '1.00'
                  estimated_price: '50.00'
                  estimated_quantity: '0.67911'
                  exit_costs: '0.50'
                  exit_costs_pct: '1.00'
                  impact_final_year: '0.50'
                  impact_final_year_pct: '1.00'
                  impact_first_year: '0.50'
                  impact_first_year_pct: '1.00'
                  impact_subsequent_year: '0.28'
                  impact_subsequent_year_pct: '0.55'
                  kid: https://mocked.test/kid/IE00B441G979.pdf
                  product_costs: '0.28'
                  product_costs_pct: '0.55'
                  running_costs: '0.28'
                  running_costs_pct: '0.55'
                  service_costs_total: '0.50'
                  service_costs_total_pct: '1.00'
                  third_party_grants: '0.00'
                  third_party_grants_pct: '0.00'
                sca:
                  required: false
                  challenge: am9icy5sZW1vbi5tYXJrZXRz
                side: buy
                status: confirmed
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /accounts/{account_id}/batch_orders:
    post:
      summary: Create Batch Order
      tags:
      - Batch Orders
      operationId: create_batch_order
      parameters:
      - name: account_id
        required: true
        schema:
          title: Account Identifier
          type: string
          description: 'An account identifier.

            '
        in: path
        example: cusa_c2c3f89ec0524b6e818ce00c16e4897f
      - name: LMG-Data-Privacy-Access-Principal
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Principal
        in: header
      - name: LMG-Data-Privacy-Access-Justification
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Justification
        in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBatchOrderRequest'
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchOrderResponse'
              example:
                amount: '50.00'
                appropriateness_check:
                  consent_confirmed_at: null
                  consent_required: true
                created_at: '2023-07-14T16:35:19.203369+00:00'
                currency: EUR
                fee: '0.50'
                history:
                - status: created
                  timestamp: '2023-07-14T16:35:19.203369+00:00'
                id: bord_0fef2e8b7962404d94454d8c47caa364
                instrument: IE00B441G979
                quantity: null
                regulatory_disclosures:
                  entry_costs: '0.50'
                  entry_costs_pct: '1.00'
                  estimated_price: '50.00'
                  estimated_quantity: '0.67911'
                  exit_costs: '0.50'
                  exit_costs_pct: '1.00'
                  impact_final_year: '0.50'
                  impact_final_year_pct: '1.00'
                  impact_first_year: '0.50'
                  impact_first_year_pct: '1.00'
                  impact_subsequent_year: '0.28'
                  impact_subsequent_year_pct: '0.55'
                  kid: https://mocked.test/kid/IE00B441G979.pdf
                  product_costs: '0.28'
                  product_costs_pct: '0.55'
                  running_costs: '0.28'
                  running_costs_pct: '0.55'
                  service_costs_total: '0.50'
                  service_costs_total_pct: '1.00'
                  third_party_grants: '0.00'
                  third_party_grants_pct: '0.00'
                sca:
                  required: false
                  challenge: am9icy5sZW1vbi5tYXJrZXRz
                side: buy
                status: created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: List Batch Orders
      operationId: list_batch_orders
      tags:
      - Batch Orders
      parameters:
      - name: account_id
        required: true
        schema:
          title: Account Identifier
          type: string
        in: path
        example: cusa_c2c3f89ec0524b6e818ce00c16e4897f
        description: 'An account identifier.

          '
      - name: cursor
        required: false
        schema:
          title: Cursor
          type: string
        description: 'A pagination cursor.  When you receive a paginated response containing the property `pagination.next_cursor`, you can pass its value here to get the next page of results for your query.

          A cursor will include filter parameters, so there is not need to specify both the `cursor` and any other filter parameter.

          '
        in: query
      - name: limit
        required: false
        schema:
          title: Limit
          maximum: 100
          exclusiveMinimum: 0
          type: integer
          default: 100
        in: query
        description: 'In order to customize the number of elements returned, you can provide a limit here.  The service will not return more elements than specified.

          '
      - name: status
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/OrderStatus'
          title: Status
          description: 'Use this parameter to filter for batch orders of one specific status.

            '
      - name: LMG-Data-Privacy-Access-Principal
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Principal
        in: header
      - name: LMG-Data-Privacy-Access-Justification
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Justification
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_BatchOrderResponse_'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /accounts/{account_id}/batch_orders/{order_id}:
    get:
      summary: Get Batch Order
      tags:
      - Batch Orders
      operationId: get_batch_order
      parameters:
      - name: account_id
        required: true
        schema:
          title: Account Identifier
          type: string
        in: path
        example: cusa_c2c3f89ec0524b6e818ce00c16e4897f
        description: 'An account identifier.

          '
      - name: order_id
        required: true
        schema:
          type: string
          title: Order Identifier
        in: path
        example: bord_0fef2e8b7962404d94454d8c47caa364
        description: 'A batch order identifier.

          '
      - name: LMG-Data-Privacy-Access-Principal
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Principal
        in: header
      - name: LMG-Data-Privacy-Access-Justification
        required: true
        schema:
          type: string
          title: Lmg-Data-Privacy-Access-Justification
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchOrderResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    StrongCustomerAuthenticationRequest:
      title: StrongCustomerAuthenticationRequest
      description: 'An object representing a strong customer authentication challenge.

        '
      properties:
        required:
          type: boolean
          title: Required
          description: 'Indication of strong customer authentication requirement.  If this value is `true`, the next request needs to include a solution to the challege (e.g. in the `sca` property for batch order confirmation).

            '
        challenge:
          type: string
          title: Challenge
          description: 'A base64-url encoded blob of data.  Sign the decoded data using a registered authenticator and include the signature in the next request (e.g. in the `sca` property for batch order confirmation).

            '
      type: object
      required:
      - required
      - challenge
    ActorResponse:
      properties:
        type:
          type: string
          const: person
          title: Type
          description: 'The actor type.  For the time being, the only valid value is `"person"`.

            '
        person:
          type: string
          title: Person Identifier
          description: 'A person identifier.  This identifier specifies the individual performing an action (e.g. create/confirm order).

            '
      type: object
      required:
      - type
      - person
      title: ActorResponse
      description: 'An object describing the individual performing an action.

        '
    Page_BatchOrderResponse_:
      title: Page of BatchOrderResponse
      properties:
        data:
          items:
            $ref: '#/components/schemas/BatchOrderResponse'
          type: array
          title: Data
          description: 'The elements of the response.

            '
        pagination:
          $ref: '#/components/schemas/Pagination'
      type: object
      required:
      - data
      - pagination
    OrderRejectionReason:
      type: string
      enum:
      - insufficient_buying_power
      - insufficient_available_securities
      - insufficient_order_amount
      - rejected_by_exchange
      - manual_rejection
      - unknown
      title: Order rejection reason
      description: 'The reason why an order was rejected. Only populated when the order status is `rejected`.

        <ul> <li><code>insufficient_buying_power</code> - Customer does not have enough buying power for buy order</li> <li><code>insufficient_available_securities</code> - Customer does not have enough available securities for sell order</li> <li><code>insufficient_order_amount</code> - Order amount is not enough to buy at least one unit of the instrument</li> <li><code>rejected_by_exchange</code> - Order was rejected by the exchange</li> <li><code>manual_rejection</code> - Order was manually rejected</li> <li><code>unknown</code> - Rejection reason could not be determined</li> </ul>

        '
      example: insufficient_buying_power
    StatusChangeResponse:
      description: 'An object representing a change in an order.

        '
      properties:
        status:
          $ref: '#/components/schemas/OrderStatus'
        timestamp:
          type: string
          format: date-time
          title: Timestamp
          description: 'The timestamp of the event.  It represents the point in time at which the order was updated.

            '
          example: '2023-06-23T07:29:55.465000+00:00'
        actor:
          $ref: '#/components/schemas/ActorResponse'
        reason:
          allOf:
          - $ref: '#/components/schemas/OrderRejectionReason'
          nullable: true
          description: 'The reason why this order was rejected. Only populated when the order status is `rejected`.

            '
      type: object
      required:
      - status
      - timestamp
      title: StatusChange[OrderStatus]
    CreateBatchOrderRequestBuy:
      properties:
        side:
          $ref: '#/components/schemas/Side'
        instrument:
          type: string
          maxLength: 255
          title: Instrument
          description: 'An ISIN (International Securities Identification Number) according to ISO 6166. This value uniquely identifies the instrument to be bought/sold.

            '
        amount:
          type: string
          format: number
          exclusiveMinimum: 0
          title: Amount
          description: 'The amount of cash to invest with this batch order.

            '
        fee:
          type: string
          format: number
          minimum: 0
          title: Fee
          description: 'The fee that will be charged by lemon.markets on your behalf.

            '
        currency:
          type: string
          maxLength: 3
          minLength: 3
          title: Currency
          example: EUR
          description: 'An ISO 4217 three-letter currency code. Its value represents the currency for the amount and fee listed here. The only currently available currency is `"EUR"`.

            '
      example:
        side: buy
        instrument: IE00B441G979
        amount: '50.00'
        currency: EUR
        fee: '0.50'
      type: object
      required:
      - side
      - instrument
      - amount
      - fee
      - currency
      title: CreateBatchOrderRequest
    OrderStatus:
      type: string
      enum:
      - accepted
      - canceled
      - canceling
      - confirmed
      - created
      - executed
      - rejected
      title: OrderStatus
      description: 'A category representing the state of an order:

        <ul> <li><code>accepted</code> <li><code>canceled</code> <li><code>canceling</code> <li><code>confirmed</code> <li><code>created</code> <li><code>executed</code> <li><code>rejected</code> </ul>

        '
    ConfirmBatchOrderRequest:
      properties:
        appropriateness_consent:
          type: boolean
          title: Appropriateness Consent
          description: 'A value indicating if a user has explicitly agreed to place the order after reading the appropriateness warning.

            **NOTE:** If the batch order object indicated no need to provide the appropriateness consent, you can send `null` or omit the value.

            '
        sca:
          $ref: '#/components/schemas/SCAConfirmation'
      type: object
      title: ConfirmBatchOrderRequest
    SCAConfirmation:
      title: Strong Customer Authentication
      description: 'An object representing the confirmation for strong customer authentication.

        '
      properties:
        client_credential_id:
          type: string
          title: Client Credential Identifier
          description: 'The client-side identifier of the authenticator used to generate the signature.

            '
        signature:
          type: string
          title: Signature
          description: 'The base64-url encoded DER form of the signature for `challenge` using the private key for the public key that was registered as an authenticator.

            '
      type: object
      required:
      - client_credential_id
      - signature
    ErrorResponse:
      title: ErrorResponse
      required:
      - message
      type: object
      properties:
        message:
          title: Message
          type: string
    Side:
      type: string
      enum:
      - buy
      - sell
      title: Side
      description: 'A category to represent the side of a customer''s order:

        <ul> <li><code>buy</code>: Buy shares of an instrument and pay with cash. <li><code>sell</code>: Sell shares of an instrument and receive cash. </ul>

        '
    CreateBatchOrderRequest:
      oneOf:
      - $ref: '#/components/schemas/CreateBatchOrderRequestBuy'
      - $ref: '#/components/schemas/CreateBatchOrderRequestSell'
      discriminator:
        propertyName: side
        mapping:
          buy: '#/components/schemas/CreateBatchOrderRequestBuy'
          sell: '#/components/schemas/CreateBatchOrderRequestSell'
    BatchOrderResponse:
      properties:
        id:
          type: string
          title: Batch Order Identifier
          example: bord_353dc0fa58ba4ab7b8bd66430d04dd53
          description: 'The unique identifier for this batch order.

            '
        created_at:
          type: string
          format: date-time
          title: Created At
          description: 'The timestamp of the batch order.  It represents the point in time at which the batch order was created.

            '
        side:
          $ref: '#/components/schemas/Side'
        instrument:
          type: string
          title: Instrument
          description: 'An ISIN (International Securities Identification Number) according to ISO 6166. This value uniquely identifies the instrument to be bought/sold.

            '
        amount:
          type: string
          format: number
          title: Amount
          description: 'The amount of cash for a buy order, `null` for a sell order.

            **NOTE:** We may evolve the API to allow quantity-based buy orders and amount-based sell orders. We do not recommend to rely on the current behavior.

            '
        quantity:
          type: string
          format: number
          exclusiveMinimum: 0
          title: Quantity
          description: 'The quantity of shares for a sell order, `null` for a buy order.

            **NOTE:** We may evolve the API to allow quantity-based buy orders and amount-based sell orders. We do not recommend to rely on the current behavior.

            '
        fee:
          type: string
          format: number
          title: Fee
          description: 'The fee that will be charged by lemon.markets on your behalf.

            '
        currency:
          type: string
          maxLength: 3
          minLength: 3
          title: Currency
          example: EUR
          description: 'An ISO 4217 three-letter currency code. Its value represents the currency for the amount and fee listed here. The only currently available currency is `"EUR"`.

            '
        status:
          $ref: '#/components/schemas/OrderStatus'
        history:
          items:
            $ref: '#/components/schemas/StatusChangeResponse'
          type: array
          title: History
        regulatory_disclosures:
          $ref: '#/components/schemas/broker__apps__api__types__RegulatoryDisclosureResponse'
        appropriateness_check:
          $ref: '#/components/schemas/AppropriatenessCheckWarningResponse'
        sca:
          $ref: '#/components/schemas/StrongCustomerAuthenticationRequest'
      type: object
      required:
      - id
      - created_at
      - side
      - instrument
      - fee
      - currency
      - status
      - history
      title: BatchOrderResponse
    broker__apps__api__types__RegulatoryDisclosureResponse:
      description: 'An object describing regulatory information, such as expected prices, quantities and costs as well as links to relevant documents.

        '
      required:
      - estimated_amount
      - estimated_price
      - estimated_quantity
      - service_costs_total
      - service_costs_total_pct
      - third_party_grants
      - third_party_grants_pct
      - exit_costs
      - exit_costs_pct
      properties:
        kid:
          type: string
          format: uri
          title: Key Investor Document (KID)
          description: 'If present, a document that needs to be made available to the user.  A copy of this document will be added to the user''s `/documents` eventually.

            '
        estimated_amount:
          type: string
          format: number
          title: Estimated Amount
          description: 'An indication of the amount based on the most recent market data.

            **NOTE:** This information is indicative only and does not have to match the final execution price.

            '
        estimated_price:
          type: string
          format: number
          title: Estimated Price
          description: 'A price indication based on the most recent market data.

            **NOTE:** This information is indicative only and does not have to match the final execution price.

            '
        estimated_quantity:
          type: string
          format: number
          exclusiveMinimum: 0
          title: Estimated Quantity
          description: 'A quantity indication based on the most recent market data.

            **NOTE:** This information is indicative only and does not have to match the final execution quantity.

            '
        service_costs_total:
          type: string
          format: number
          title: Service Costs Total (absolute)
          description: 'Cost of investment services provided by lemon.markets; specified using the order''s currency.

            '
        service_costs_total_pct:
          type: string
          format: number
          title: Service Costs Total (relative)
          description: 'Relative value of `servic_costs_total` in relation to the total value of the order; specified in percentage points (`"0.23"` means 0.23%).

            '
        entry_costs:
          type: string
          format: number
          title: Entry Costs (absolute)
          description: 'The investment service costs related to the buy order; specified using the order''s currency.

            '
        entry_costs_pct:
          type: string
          format: number
          title: Entry Costs (relative)
          description: 'Relative value of `entry_costs` in relation to the total value of the order; specified in percentage points (`"0.23"` means 0.23%).

            '
        third_party_grants:
          type: string
          format: number
          title: Third Party Grants (absolute)
          description: 'Inducements paid to the broker by third parties; specified using the order''s currency.

            '
        third_party_grants_pct:
          type: string
          format: number
          title: Third Party Grants (relative)
          description: 'Relative value of `third_party_grants` in relation to the total value of the order; specified in percentage points (`"0.23"` means 0.23%).

            '
        product_costs:
          type: string
          format: number
          title: Product Costs (absolute)
          description: 'The product cost associated with owning the product; specified using the order''s currency.

            '
        product_costs_pct:
          type: string
          format: number
          title: Product Costs (relative)
          description: 'Relative value of `product_costs` in relation to the total value of the order; specified in percentage points (`"0.23"` means 0.23%).

            '
        running_costs:
          type: string
          format: number
          title: Running Costs (absolute)
          description: 'The investment service cost associated with owning the product; specified using the order''s currency.

            '
        running_costs_pct:
          type: string
          format: number
          title: Running Costs (relative)
          description: 'Relative value of `running_costs` in relation to the total value of the order; specified in percentage points (`"0.23"` means 0.23%).

            '
        exit_costs:
          type: string
          format: number
          title: Exit Costs (absolute)
          description: 'The service costs related to a sell order; specified using the order''s currency.

            **Note:** In case of a buy order, this reflects an estimate of a corresponding sell order.

            '
        exit_costs_pct:
          type: string
          format: number
          title: Exit Costs (relative)
          description: 'Relative value of `exit_costs` in relation to the total value of the order; specified in percentage points (`"0.23"` means 0.23%).

            '
        acquisition_costs:
          type: string
          title: Acquisition Costs
        acquisition_costs_pct:
          type: string
          title: Acquisition Costs Pct
        custody_costs:
          type: string
          title: Custody Costs
        custody_costs_pct:
          type: string
          title: Custody Costs Pct
        impact_first_year:
          type: string
          format: number
          title: Impact First Year (absolute)
          description: 'An indication of the costs incurred during the first year of ownership; specified using the order''s currency. This includes both product and investment service costs.

            **Note:** If the security is sold during the first year, the cost might be even higher.

            '
        impact_first_year_pct:
          type: string
          format: number
          title: Impact First Year (relative)
          description: 'Relative value of `impact_first_year` in relation to the total value of the order; specified in percentage points (`"0.23"` means 0.23%).

            '
        impact_subsequent_year:
          type: string
          format: number
          title: Impact Subsequent Year (absolute)
          description: 'An indication of the costs incurred during a year of ownership without transactions; specified using the order''s currency. This include both product and investment service costs.

            '
        impact_subsequent_year_pct:
          type: string
          format: number
          title: Impact Subsequent Year (relative)
          description: 'Relative value of `impact_subsequent_year` in relation to the total value of the order; specified in percentage points (`"0.23"` means 0.23%).

            '
        impact_final_year:
          type: string
          format: number
          title: Impact Final Year (absolute)
          description: 'An indication of the cost incurred during the last year of ownership; specified using the order''s currency. This include both product and investment service cost.

            **Note:** If the security is sold during the first year, the cost might be even higher.

            '
        impact_final_year_pct:
          type: string
          format: number
          title: Impact Final Year (relative)
          description: 'Relative value of `impact_final_year` in relation to the total value of the order; specified in percentage points (`"0.23"` means 0.23%).

            '
      type: object
      title: RegulatoryDisclosureResponse
    AppropriatenessCheckWarningResponse:
      title: AppropriatenessCheckWarningResponse
      description: 'An object representing the requirements for explicit confirmation of an appropriateness warning.

        '
      type: object
      properties:
        consent_required:
          type: boolean
          title: Consent Required
          description: 'Requirement indicator for the appropriateness warning.

            **NOTE:** If this value is `true`, the frontend must present a warning to the user as outlined in your onboarding documentation.

            '
        consent_confirmed_at:
          type: string
          format: date-time
          title: Consent Confirmed At
          description: 'A timestamp representing the point in time at which the user has confirmed the appropriateness warning.  If the user hasn''t done this yet, the value will be `null`.

            '
      required:
      - consent_required
    Pagination:
      title: Pagination
      type: object
      properties:
        next_cursor:
          title: Cursor for Next Page
          type: string
          description: 'When fetching long lists of elements, you can use our pagination feature to fetch batches of data.  If a response contains the property `pagination.next_cursor`, you can pass its value via the query item `cursor` to generate the request for the next batch of data.

            '
      description: 'Information about accessing elements beyond the ones that were returned.

        '
      example:
        next_cursor: <opaque-data>
    CreateBatchOrderRequestSell:
      properties:
        side:
          $ref: '#/components/schemas/Side'
        instrument:
          type: string
          maxLength: 255
          title: Instrument
          description: 'An ISIN (International Securities Identification Number) according to ISO 6166. This value uniquely identifies the instrument to be bought/sold.

            '
        quantity:
          type: string
          format: number
          exclusiveMinimum: 0
          title: Quantity
          description: 'Specify the quantity of shares for the instrument to be sold.

            '
        fee:
          type: string
          format: number
          minimum: 0
          title: Fee
          description: 'The fee that will be charged by lemon.markets on your behalf.

            '
        currency:
          type: string
          maxLength: 3
          minLength: 3
          title: Currency
          example: EUR
          description: 'An ISO 4217 three-letter currency code. Its value represents the currency for the fee listed here. The only currently available currency is `"EUR"`.

            '
      example:
        side: sell
        instrument: IE00B441G979
        quantity: '1.23456'
        currency: EUR
        fee: '0.50'
      type: object
      required:
      - side
      - instrument
      - quantity
      - fee
      - currency
      title: CreateBatchOrderRequest
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
